### ISSUE TITLE
Projects Upgrade

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/rock-band#94]
## Before
- [x] Check if project could be archived
- [x] Check and resolve any outstanding issues
- [x] Check and resolve any outstanding pull requests
- [x] Check branch and master are equal

## Projects site
- [x] Check [projects site](https://learning-admin.raspberrypi.org) for feedback
- [x] Check tags are correct (curriculum, hardware, software, interests and site-areas)

## Meta
- [x] Increment version number
- [x] Update last tested date
- [x] Remove redundant meta tags (ingredient, duration, theme, curriculum, interest, site area, hardware, software, original_url)
- [x] Remove step numbers from meta (and any step names)

## Directory structure and files
- [x] `resources` directory containing all need assets (within `en`)
- [x] `solutions` directory containing all needed solutions (within `en`)
- [x] Add LICENSE.md if not exist
- [x] Add a CONTRIBUTING.md if there isn’t one
- [x] Update the README.md to link to the project, license and contributing
- [ ] Compile all solutions and resources directories into a resources.zip and solutions.zip as top level files

## On [Shortlinks](rpf.io/admin)
- [ ] Create rpf.io/project-name-go to link to the `resources.zip`
- [ ] Create rpf.io/project-name-get to link to the `solutions.zip`
- [ ] Create rpf.io/project-name-on to link to the online starter file if needed
- [ ] Create rpf.io/project-name-off to link to the offline starter file if needed

## Ingredients
- [x] Update all ingredients used within a project, particularly with regard to new code syntax

## Step 1
- [x] Add interactive showcase of project or GIF to step 1 within `--- no-print ---`
- [x] Add image of project within `--- print-only ---`
- [x] Add instructions for engaging with showcase before the showcase embed
- [x] *What you will learn* inside a collapse (these are the learning objectives)
- [x] *What you will need* inside a collapse
  - [x] Contains a list of hardware
  - [x] Contains a list of software
  - [x] Contains a link to the rpf.io/project-name-go
- [x] *Additional notes for educators* inside a collapse
  - [x] Contains a link to the rpf.io/project-name-get
  - [x] “If you need to print this project, please use the printer-friendly version.”

## Step 2
- [x] Collapse content "Getting Started" if needed
  - [x] Short link online resource and offline resource if needed.

## Tasks
- [x] Where learner is asked to do something use the `--- task ---` syntax
- [x] If the solution to a task requires some independence then add a hint within the task.

## Code
- [x] Add image of sprite above the code block it is referring to if Scratch (64px in smallest dimension)
- [x] Screenshots replaced with [markdown](https://docs.google.com/document/d/1w7s9TzCj3lVf-rh4umQlLyN8e_wbg9ptZizmQPvfwHw/edit#heading=h.6jpkqdmev6a4)
- [x] If project is in Code Club book - check that the code matches

## Hints
- [x] 1 per step max

## Ingredients
- [x]  1 per step max

## Challenges
- [x] Each Challenge has it's own step
- [x] Must have challenge at end of project
- [x] Challenge can be skipped and project still completed

## What next?
- [x] Add a what next step at the end with links to other projects in the series or related projects.

## Fall-backs
- [x] For all animated and embedded content include `--- no-print ---` and `--- print-only ---` sections

## Embeds
- [x] Check Scratch and Trinket embeds use official account

## Translations
- [x] Open issue for Nina citing that the project has been changed
